services:
  # ThingsBoard IoT Gateway Service Configuration
  tb-gateway:
    image: thingsboard/tb-gateway:3.7-stable
    container_name: tb-gateway
    restart: always
    privileged: true

    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - host=host.docker.internal
      - port=1883
      - accessToken=ODyKE7h3knqdIwdcIEcm

    volumes:
      - tb-gw-config:/thingsboard_gateway/config
      - tb-gw-logs:/thingsboard_gateway/logs
      - ./tb-gw-extensions:/thingsboard_gateway/extensions
      - /var/run/dbus:/var/run/dbus #
      - /dev:/dev #                 # Necesario para usar Bluetooth

  ota-transfer:
    build:
      context: ./ota-transfer-service
    container_name: ota-transfer
    ports:
      - "5000:5000"
    volumes:
      - tb-gw-config:/tb-gw-config/
      - /var/run/dbus:/var/run/dbus #
      - /dev:/dev #                 # Necesario para usar Bluetooth
    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - tb-gateway

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    # privileged: true
    volumes:
      - ./lora-bridge/mosquitto_config:/mosquitto/config
      - mosquitto-log:/mosquitto/log
    ports:
      - "1884:1883"

  lora-reliability-manager:
    build:
      context: ./lora-bridge/reliability_manager
    container_name: lora-reliability-manager
    extra_hosts:
      # Necessary mapping for Linux
      - "host.docker.internal:host-gateway"
    environment:
      - mqtt_user=device
      - mqtt_password=updatable
      # Lista separada por comas de los identificadores de dispositivos LoRa en la red
      # (se obtienen a partir de la MAC Wifi del dispositivo)
      - device_id_list=f024f9b18b08
    depends_on:
      - mqtt-broker

# Volumes declaration for configurations, extensions and configuration
volumes:
  tb-gw-config:
    name: tb-gw-config
  tb-gw-logs:
    name: tb-gw-logs
  tb-gw-extensions:
    name: tb-gw-extensions
  mosquitto-log:
    name: mosquitto-log
